name: Build & upload to Play Console

on:
  push:
    branches:
      - master
#    tags: 'release/*'

jobs:
  setup:
    name: Build and Upload to Firebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Create google-services.json
        run: cat /home/runner/work/Roar/Roar/androidApp/google-services.json | base64
      - name: Insert google-services.json data
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA | base64 -di > /home/runner/work/Roar/Roar/androidApp/google-services.json

      - name: Build AAB
        run: bash ./gradlew bundleRelease

      - name: Sign AAB
        id: sign_aab
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: androidApp/release
          signingKeyBase64: ${{ secrets.SIGNINGKEYBASE64 }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTOREPASSWORD }}
          keyPassword: ${{ secrets.KEYSTOREPASSWORD }}

      - name: Make artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-release-signed
          path: ${{steps.sign_aab.outputs.signedReleaseFile}}

      - name: Upload release
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          packageName: com.gaoyun.roar.android
          releaseFiles: ${{steps.sign_aab.outputs.signedReleaseFile}}
          track: internal
          status: inProgress
          inAppUpdatePriority: 2
          userFraction: 1
